name: ez_mooc
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  youtube_explode_dart: ^2.0.2
  youtube: ^0.0.1
  youtube_player_flutter: ^8.1.2
  percent_indicator: ^4.2.3
  flutter_animation_progress_bar: ^2.3.1
  simple_circular_progress_bar: ^1.0.2
  google_fonts: ^6.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - images/
  fonts:
    - family: Kanit
      fonts:
        - asset: fonts/Kanit-Regular.ttf
          weight: 700


